name: Publish Release APK

on:
  push:
    tags: [ "*" ]

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build Release APK
        run: ./gradlew assembleRelease
      - name: Publish APK
        uses: CosmicIsAryan/action-release-apk@master
        env:
          GITHUB_TOKEN: ${{ ghp_td6so0ei6akemsPE61zfprK43P4fUI3s89z4.TOKEN }}
          APP_FOLDER: app
          RELEASE_TITLE: New Build